name: continuous_integration_build
on:
  push:
    branches: ["core"]
  pull_request:
    branches: ["*"]
env:
  target_device_version: 15.5
jobs:
  build:
    name: continuous_integration_build
    runs-on: macos-15
    steps:
      - name: git_initialization
        run: git config --global init.defaultBranch core
      - name: continuous_integration:repository->checkout
        uses: actions/checkout@v5
        with:
          path: exxx
      - name: checkout_cer0
        uses: actions/checkout@v5
        with:
          repository: alic3dev/cer0
          path: cer0
      - name: checkout_clic3
        uses: actions/checkout@v5
        with:
          repository: alic3dev/clic3
          path: clic3
      - name: checkout_math_c
        uses: actions/checkout@v5
        with:
          repository: alic3dev/math_c
          path: math_c
      - name: make_clic3
        run: cd clic3 && make clic3_without_metal target_device_version=${{ env.target_device_version }}
      - name: make_math_c
        run: cd math_c && make math_c_without_metal target_device_version=${{ env.target_device_version }}
      - name: make_cer0
        run: cd cer0 && make target_device_version=${{ env.target_device_version }}
      - name: make_exxx
        run: cd exxx && make target_device_version=${{ env.target_device_version }}
